cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: File-demo-application
    stack:
      auto: false
file:
  temp:
    directory: C:\\uploadTest

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chatting-total
    username: chatUser
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0B
      location: C:\\uploadTest
      max-file-size: 15MB
      max-request-size: 15MB

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"