cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: file-demo-application
    stack:
      auto: false

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0B
      location: C:\\uploadTest
      max-file-size: 15MB
      max-request-size: 15MB

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"